In [1]:
#load the titanic data
import pandas as pd
titanic_data = pd.read_csv('tested.csv')

In [2]:
#read the data loaded
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [5]:
titanic_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [8]:
#fill in the age column with the median
titanic_data['Age']=titanic_data['Age'].fillna(titanic_data['Age'].median())
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [9]:
titanic_data['Fare']=titanic_data['Fare'].fillna(titanic_data['Fare'].median())
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         418 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [10]:
#drop column cabin
titanic_data=titanic_data.drop('Cabin',axis=1)
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         418 non-null    float64
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 36.1+ KB

In [11]:
#we come up with a new variable called identity
identity=titanic_data[["PassengerId", "Name"]]
identity.head()

   PassengerId                                          Name
0          892                              Kelly, Mr. James
1          893              Wilkes, Mrs. James (Ellen Needs)
2          894                     Myles, Mr. Thomas Francis
3          895                              Wirz, Mr. Albert
4          896  Hirvonen, Mrs. Alexander (Helga E Lindqvist)

In [ ]:
#dumify categorical data 
#do we need to dumify tickets ?
#no need to dumify passengerid and name because they are identifiers

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, classification_report
import statsmodels.api as sm 
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [14]:
#dumify the data
titanic_data=pd.get_dummies(titanic_data, columns=['Pclass', 'Embarked'],drop_first=True, dtype=int)
titanic_data.head()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,892,0,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,0,1,1,0
1,893,1,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,0,1,0,1
2,894,0,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,1,0,1,0
3,895,0,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,0,1,0,1
4,896,1,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,0,1,0,1

In [15]:
le=LabelEncoder()
titanic_data['Sex']=le.fit_transform(titanic_data['Sex'])
titanic_data.head()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,892,0,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,0,1,1,0
1,893,1,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,363272,7.0000,0,1,0,1
2,894,0,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,1,0,1,0
3,895,0,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,0,1,0,1
4,896,1,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,3101298,12.2875,0,1,0,1

In [ ]:
#lets group by so that we can know that who surviverd in the sex column
gender_survived=titanic_data.groupby(['Sex'])['Survived'].agg('count')
gender_survived

Sex
0    152
1    266
Name: Survived, dtype: int64

In [18]:
survived=titanic_data[titanic_data['Survived']==1]
survived.head()

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
1,893,1,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,363272,7.0000,0,1,0,1
4,896,1,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,3101298,12.2875,0,1,0,1
6,898,1,"Connolly, Miss. Kate",0,30.0,0,0,330972,7.6292,0,1,1,0
8,900,1,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",0,18.0,0,0,2657,7.2292,0,1,0,0
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",0,23.0,1,0,21228,82.2667,0,0,0,1

In [21]:
#group by the sex to know which gender survived more 
survived_gender=survived.groupby(['Sex'])['Survived'].agg('count')
survived_gender

Sex
0    152
Name: Survived, dtype: int64

In [23]:
survived['Sex'].value_counts()

Sex
0    152
Name: count, dtype: int64